// Generated by https://quicktype.io

export interface ListarClientesProps {
  tipoCliente: string;
  nombres: null | string;
  apellidos: null | string;
  dni: null | string;
  razonSocial: null | string;
  ruc: null | string;
  id: number;
  createdAt: Date;
  isActive: boolean;
}
