// Generated by https://quicktype.io

export interface ListarProductosActivoProps {
    idProducto: number;
    descripcion: string;
    precio:      number;
    stock:       number;
    imageUrl:    string;
    proveedor:   string;
    marca:       string;
    categoria:   string;
}
