// Generated by https://quicktype.io

export interface ProductoRegistrarProps {
    descripcion: string;
    precio:      number;
    stock:       number;
    imageUrl:    string;
    proveedorId: number;
}
