// Generated by https://quicktype.io

export interface ProductoRegistrarProps {
  descripcion: string;
  precio: number;
  stock: number;
  imageUrl: string;
  proveedorId: string;
  marcaId : string;
  categoriaId: string;
}
