// Generated by https://quicktype.io

export interface UserListProps {
    id:             string;
    userName:       string;
    email:          string;
    createdAt:      Date;
    isActive:       boolean;
    employeeId:     number;
    firstName:      string;
    lastNameFather: string;
    lastNameMother: string;
    position:       string;
    roleName:       string;
}
