// Generated by https://quicktype.io

export interface UserListProps {
    id:             string;
    userName:       string;
    email:          string;
    createdAt:      Date;
    isActive:       boolean;
    employeeId:     number;
    firstName:      string;
    lastNameFather: string;
    lastNameMother: string;
    position:       string;
    roleName:       string;
}



export interface UserRegisterProps {
    employeeId: number;
    userName: string;
    email: string;
    password: string;
    roleId: string;
  
}

export interface UserRegisterErrorProps {
    employeeId: number;
    userName: string;
    email: string;
    password: string;
    roleId: string;
 
}

export interface UserLoginProps {
    email: string;
    password: string;
}   

export interface UserLoginErrorProps {
    email: string;
    password: string;
}
