export { default as HeroWithCarousel } from "./carousel/HeroWithCarousel";
export { default as ComplexNavbar } from "./navbar/ComplexNavbar";
export { default as Footer } from "./footer/Footer";
export { default as Products } from "./products/products";
export { default as CategoriasGrid } from "./categories/CategoriasGrid";
export { default as LoginForm } from "./login/Login";
export { default as ContactForm } from "./contact/Contact";
export { default as EmployeeFormRegister } from "./employeeRegister/employeeRegister";
export { default as EmployeeFormList } from "./employeeList/employeeList";
export { default as EmployeeFormView } from "./employeeView/employeeView";
export { default as Dashboard} from "./dashboard/dashboard";
