export { default as HeroWithCarousel } from "./carousel/HeroWithCarousel";
export { default as ComplexNavbar } from "./navbar/ComplexNavbar";
export { default as Footer } from "./footer/Footer";
export { default as Products } from "./products/products";
export { default as CategoriasGrid } from "./categories/CategoriasGrid";
export { default as LoginForm } from "./login/Login";
export { default as ContactForm } from "./contact/Contact";
export { default as RegisterFormEmployee } from "./employeeRegister/employeeRegister";
export { default as ListFormEmployee } from "./employeeList/empleadoList";
